<GlowButton>:
    border_radius: ('5dp', )
    border_width: ('1dp', )
    padding: ('5dp', )
    GlowBoxLayout:
        id: glow_button_container
        orientation: 'horizontal'
        spacing: root.spacing
        adaptive_size: True
        GlowLabel:
            id: glow_button_text
            text: root.text if root.text else ''
            font_style: root.font_style
            pos_hint: {'center_y': 0.5}
            color: root._text_color
            adaptive_size: True
